src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Suspect_Enabled__c</fullName>
        <label>Suspect Enabled</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Defect__c.object
<CustomObject>
    <description>This is a master object in Quality Central.</description>
    <fields>
        <fullName>Count_Compare_Date__c</fullName>
        <formula>NOW() - Count_Compare_Value__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Count Compare Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Count_Compare_Value__c</fullName>
        <formula>IF(
   ISPICKVAL( Count_Total_Time_Unit__c, &quot;Day&quot;),1*  Count_Total_Time_as_Num__c ,
   IF(ISPICKVAL(Count_Total_Time_Unit__c, &quot;Week&quot;),7* Count_Total_Time_as_Num__c,
      IF(ISPICKVAL(Count_Total_Time_Unit__c, &quot;Month&quot;),30* Count_Total_Time_as_Num__c,
         IF(ISPICKVAL(Count_Total_Time_Unit__c, &quot;Year&quot;),365* Count_Total_Time_as_Num__c,0)  
        )
      )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Count Compare Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_Total_as_Num__c</fullName>
        <label>Count Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Defect__c</fullName>
        <formula>Name + IF(ISBLANK(Defect_Code__c), &apos;&apos;, &apos;(&apos; + Defect_Code__c + &apos;)&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Defect</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Suspect_Enabled__c</fullName>
        <label>Suspect Enabled</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volume_Compare_Date__c</fullName>
        <formula>NOW() - Volume_Compare_Value__c</formula>
        <label>Volume Compare Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Volume_Compare_Value__c</fullName>
        <formula>IF(
   ISPICKVAL(Volume_Total_Time_Unit__c, &quot;Day&quot;),1* Volume_Total_Time_as_Num__c,
   IF(ISPICKVAL(Volume_Total_Time_Unit__c, &quot;Week&quot;),7* Volume_Total_Time_as_Num__c,
      IF(ISPICKVAL(Volume_Total_Time_Unit__c, &quot;Month&quot;),30* Volume_Total_Time_as_Num__c,
         IF(ISPICKVAL(Volume_Total_Time_Unit__c, &quot;Year&quot;),365* Volume_Total_Time_as_Num__c,0)  
        )
      )
)</formula>
        <label>Volume Compare Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Volume_Total_as_Num__c</fullName>
        <label>Volume Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Defect</label>
    <nameField>
        <label>Defect Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Defects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Defect_Cause__c.object
<CustomObject>
    <description>This is junction object between Defect and Cause objects.</description>
    <fields>
        <fullName>Cause__c</fullName>
        <label>Cause</label>
        <referenceTo>Cause__c</referenceTo>
        <relationshipLabel>Defect Causes</relationshipLabel>
        <relationshipName>Defect_Causes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Defect_Cause_id__c</fullName>
        <label>Defect Cause id</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Defect__c</fullName>
        <label>Defect</label>
        <referenceTo>Defect__c</referenceTo>
        <relationshipLabel>Defect Causes</relationshipLabel>
        <relationshipName>Defect_Causes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Defect Cause</label>
    <nameField>
        <displayFormat>DCN-{0000}</displayFormat>
        <label>Defect Cause Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defect Causes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/NC_Product_Defect__c.object
<CustomObject>
    <description>This is a Non Conformance - Product - Defect object.</description>
    <fields>
        <fullName>Customer_Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer/Supplier</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>NC Product Defects</relationshipLabel>
        <relationshipName>NC_Product_Defects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Defect__c</fullName>
        <label>Defect</label>
        <referenceTo>Defect__c</referenceTo>
        <relationshipLabel>NC Product Defects</relationshipLabel>
        <relationshipName>NC_Product_Defects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Lot_Numbers__c</fullName>
        <label>Product Lot Numbers</label>
        <referenceTo>Product_Lot_Numbers__c</referenceTo>
        <relationshipLabel>NC Product Defects</relationshipLabel>
        <relationshipName>NC_Product_Defects</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Suspect_Enabled__c</fullName>
        <formula>IF(ISPICKVAL(Defect__r.Suspect_Enabled__c, &quot;Yes&quot;),&quot;Yes&quot;,&quot;No&quot; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Suspect Enabled</label>
        <type>Text</type>
    </fields>
    <label>NC Product Defect</label>
    <nameField>
        <displayFormat>NCPD-{00000}</displayFormat>
        <label>NC Product Defect Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NC Product Defects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process_Defect__c.object
<CustomObject>
    <description>This is a master object in Quality Central.</description>
    <fields>
        <fullName>Defect__c</fullName>
        <label>Defect</label>
        <referenceTo>Defect__c</referenceTo>
        <relationshipLabel>Process Defects</relationshipLabel>
        <relationshipName>Process_Defects</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Process_Defect_Id__c</fullName>
        <description>Unique process defect junction record</description>
        <label>Process Defect Id</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Standard_Operational_Process__c</fullName>
        <label>Standard Operational Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Process Defects</relationshipLabel>
        <relationshipName>Process_Defects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Process Defect</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Process Defect Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Defects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process_Relationship__c.object
<CustomObject>
    <description>This is a master object in Quality Central.</description>
    <fields>
        <fullName>Operational_Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operational Process</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Process__c.Type__c</field>
                <operation>equals</operation>
                <value>Operational Process</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Process Relationship (Standard Operational Process)</relationshipLabel>
        <relationshipName>Process_Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Relationship_Id__c</fullName>
        <description>This is combination of Standard Operational Process and Operational Process so user should not crate duplicate combination.</description>
        <label>Process Relationship Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Standard_Operational_Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Standard Operational Process</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Process__c.Type__c</field>
                <operation>equals</operation>
                <value>Standard Operational Process</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Process Relationship (Operational Process)</relationshipLabel>
        <relationshipName>Process_Relationship1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process Relationship</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Process Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Relationship</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <description>This is a master object in Quality Central.</description>
    <fields>
        <fullName>Product__c</fullName>
        <formula>Name + IF(ISBLANK(Product_Number__c), &apos;&apos;, &apos;(&apos; + Product_Number__c + &apos;)&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <label>Product Family</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Family</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product_Defect__c.object
<CustomObject>
    <description>This is a master object in Quality Central.</description>
    <fields>
        <fullName>Defect__c</fullName>
        <label>Defect</label>
        <referenceTo>Defect__c</referenceTo>
        <relationshipLabel>Product Defects</relationshipLabel>
        <relationshipName>Product_Defects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Defect_Id__c</fullName>
        <label>Product Defect Id</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product Defects</relationshipLabel>
        <relationshipName>Product_Defects</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Defect</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Defects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Lot_Numbers__c.object
<CustomObject>
    <description>This is a Non Conformance - Product - Lot Number object.</description>
    <fields>
        <fullName>Customer_Supplier__c</fullName>
        <formula>IF(ISNULL(NC_Product__r.Non_Conformance__r.Customer__r.Id ) , NC_Product__r.Non_Conformance__r.Manufacturer_Supplier__r.Id  , NC_Product__r.Non_Conformance__r.Customer__r.Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer/Supplier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lot_Quantity_Affected__c</fullName>
        <label>Lot Quantity Affected</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>NC Product Lot Numbers</label>
    <nameField>
        <displayFormat>NCPLN-{00000}</displayFormat>
        <label>Lot / Bacth Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NC Product Lot Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Relationship__c.object
<CustomObject>
    <description>This is a master object in Quality Central.</description>
    <fields>
        <fullName>Product_Relationship_Id__c</fullName>
        <description>This is combination of Parent Product and Product so user should not crate duplicate combination.</description>
        <label>Product Relationship Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Relationship</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Product Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Relationship</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/QCTriggerHandler.cls
/*
 
     v1.0  Qualityze Inc(BK)        03-MAY-2016    Initial Version.
                                                   This Trigger Handler  includes objects related to Quality Central
                                                   i.e Defect Cause ,Defect ,Process Defect ,Process Relationship ,Product Relationship
     v1.1  Qualityze Inc(Bk)        09-SEp-2016    Updated Version.

*/
public with sharing class QCTriggerHandler {
    
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // QC Defect Cause start
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    
    public static void  DefectCause_BeforeTrigger(List<Defect_Cause__c> records){
        for(Defect_Cause__c pd: records)
        {
            pd.Defect_Cause_id__c= pd.Defect__c+'|'+pd.Cause__c;
        }
    }
    // QC Defect Cause End
    
    //QC Defect start
    public static void Defect_BeforeTrigger(List<Defect__c> records)
    {
       Defect_BeforeTrigger_PopulateDefectvalues(records);
    }
   
    public static void Defect_AfterTrigger(List<Defect__c> records)
    {
       Defect_AfterTrigger_UpdateAccountvalues(records);
    }
    
    public static void Defect_AfterTrigger_UpdateAccountvalues(List<Defect__c> records)
    {
      Set<Id> defectIds = new Set<Id>();

      for(Defect__c d: records)
      {
          defectIds.add(d.Id);
      }
      
      List<Account> accountListToUpdate = new List<Account>();
      Set<Id> AccountIds_SuspectEnabledYes = new Set<Id> ();
      Set<Id> AccountIds_SuspectEnabledNo = new Set<Id> ();
      
      if(defectIds.size() > 0)
      {     
          string NCProductDefectFields=QC_DynamicObjectHandler.getAccessibleFields('NC_Product_Defect__c','Id,Defect__c,Defect__r.Suspect_Enabled__c,Customer_Supplier__c,');
          List<NC_Product_Defect__c> NcProductDefectList = database.query('Select '+NCProductDefectFields+' from NC_Product_Defect__c where Defect__c IN: defectIds');
          for(NC_Product_Defect__c ncpd: NcProductDefectList )
          {
              if(!String.isEmpty(ncpd.Customer_Supplier__c) && ncpd.Defect__r.Suspect_Enabled__c == 'Yes')
              {
                 AccountIds_SuspectEnabledYes.add(ncpd.Customer_Supplier__c);     
              }
              else if(!String.isEmpty(ncpd.Customer_Supplier__c) && ncpd.Defect__r.Suspect_Enabled__c != 'Yes')
              {
                  AccountIds_SuspectEnabledNo.add(ncpd.Customer_Supplier__c);
              }
              
          }
            
          string AccountFields= QC_DynamicObjectHandler.getAccessibleFields('Account','Id,Suspect_Enabled__c');
          if(AccountIds_SuspectEnabledYes.size() > 0)
          {
              if(AccountFields!=null&&AccountFields!=''){                  
                  List<Account> accountList_SuspectEnabled = database.query('Select '+AccountFields+' from Account where Id IN: AccountIds_SuspectEnabledYes');
                  for(Account a: accountList_SuspectEnabled)
                  {
                      a.Suspect_Enabled__c = 'Yes';
                      accountListToUpdate.add(a);
                  }
              }
              
              
          }
          
          if(AccountIds_SuspectEnabledNo.size() > 0)
          {
              if(AccountFields!=null&&AccountFields!=''){  
                  List<Account> accountList_SuspectDisabled = database.query('Select '+AccountFields+' from Account where Id IN: AccountIds_SuspectEnabledNo');
                  for(Account a: accountList_SuspectDisabled)
                  {
                      a.Suspect_Enabled__c = 'No';
                      accountListToUpdate.add(a);
                  }
              }
           }
              
              if(accountListToUpdate.size() > 0)
              {
                  update accountListToUpdate;
              }
          } // Defect size If condition
    }// End of function
      
    
    public static void Defect_BeforeTrigger_PopulateDefectvalues(List<Defect__c> records)
    {
        Set<Id> DefectRecIds = new Set<Id>();
    
        for(Defect__c def : records)
        {
            if(def.Volume_total_as_Num__c != null || def.Count_Total_as_Num__c != null)
            {
                    DefectRecIds.add(def.Id);
            } // End of IF condition
   
        } // End of for Loop
        
        System.debug('-->DefectRecIds:'+DefectRecIds);
        
        List<Defect__c> DefectList = new List<Defect__c>();
        //Map<Id,String> defectId_DefectVolumeUnit = new Map<Id,String>();
        
        List<NC_Product_Defect__c> ncpdList = [Select Id,Createddate,Lastmodifieddate,defect__c,Product_Lot_Numbers__r.Lot_Quantity_Affected__c from NC_Product_Defect__c where Defect__c IN: DefectRecIds];
        
        // Iterate through defect and prepare list to uopdate defect for suspect flag
        for(Defect__c defct : records)
        {
            decimal defectQuantitycount = 0;
            integer defectCount=0;
            // iterate through nc product defect
            for(NC_Product_Defect__c ncpd: ncpdList)
            {
                if(ncpd.Defect__c == defct.Id )
                {
                    if(ncpd.Product_Lot_Numbers__r.Lot_Quantity_Affected__c != null && defct.Volume_Compare_Value__c > 0 && ncpd.Lastmodifieddate >= defct.Volume_Compare_Date__c)
                    {
                        System.debug('--> In volume loop'+ncpd.Product_Lot_Numbers__r.Lot_Quantity_Affected__c + '-->'+ defct.Volume_Compare_Value__c + '-->' +defct.Volume_Compare_Date__c);
                        defectQuantitycount += ncpd.Product_Lot_Numbers__r.Lot_Quantity_Affected__c; 
                        
                    }
                    if(defct.Count_Compare_value__c > 0 && ncpd.Lastmodifieddate >= defct.Count_Compare_Date__c)
                    {
                        System.debug('--> In count loop'+ncpd.Product_Lot_Numbers__r.Lot_Quantity_Affected__c + '-->'+ defct.Count_Compare_value__c + '-->' +defct.Count_Compare_Date__c);
                        defectCount++;
                    }
                }
            } // end of Inner for loop
        
            if(defectQuantitycount > = (decimal)defct.Volume_total_as_Num__c)
            {
                // Include defect to update suspct flag
                defct.Suspect_Enabled__c = 'Yes';
            }
            else if(defectCount >= defct.Count_Total_as_Num__c)
            {
               // Include defect to update suspct flag
                defct.Suspect_Enabled__c = 'Yes';
            }
            else
            {
                defct.Suspect_Enabled__c = 'No';
            }
        } // end of For Loop
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //QC Defect end
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //QC Process Defect start
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    
    public static void  ProcessDefect_BeforeTrigger(List<Process_Defect__c> records){
        for(Process_Defect__c pd: records)
        {
            pd.Process_Defect_Id__c= pd.Standard_Operational_Process__c+'|'+pd.Defect__c;
        }
    }
    
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //QC Process Defect end
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //QC ProcessRelationship start
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    
    public static void ProcessRelationship_BeforeTrigger(List<Process_Relationship__c > records)
    {
        for(Process_Relationship__c pr: records)
        {
            
            pr.Process_Relationship_Id__c = pr.Standard_Operational_Process__c+'|'+pr.Operational_Process__c;
        }
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //QC ProcessRelationship end
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //QC Product Defect start
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    public static void ProductDefect_BeforeTrigger(List<Product_Defect__c > records)
    {
        for(Product_Defect__c pr: records)
        {
            pr.Product_Defect_Id__c= pr.Product__c+'|'+pr.Defect__c;
        }
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //QC Product Defect End
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //QC ProductRelationship Start
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    public static void ProductRelationship_BeforeTrigger(List<Product_Relationship__c> records)
    {
        for(Product_Relationship__c pr: records)
        {
            pr.Product_Relationship_Id__c= pr.Parent_Product__c+'|'+pr.Child_Product__c;
        }
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //QC ProductRelationship end
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    
    //Number Scheme Default Number validation 
    // v1.1   start
    public static void Number_Scheme_AfterDeleteTrigger(Map<id,Number_Scheme__c> OldMap)
    {
        for(Number_Scheme__c  ns: OldMap.values())
        {
            if(ns.name=='Default Document Number'&&ns.Maxnumber__c==999999){//in case there is a need to delete this record Maxnumber__c==999999
                ns.Name.addError('cannot delete this record');//to restrict user to delete this record
            }else if(ns.Maxnumber__c!=null){
                ns.Name.addError('cannot delete this record This record is referred by other document profile ');
            }
        }
    }
    //v1.1  end
}