src/objects/CAPA__c.object
<CustomObject>
    <description>Future</description>
    <fields>
        <fullName>Followers__c</fullName>
        <label>Followers</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CAPA</label>
    <nameField>
        <displayFormat>CAPA-{00000}</displayFormat>
        <label>CAPA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Corrective and Preventive Actions</pluralLabel>
    <recordTypes>
        <fullName>CAPA</fullName>
        <active>true</active>
        <label>CAPA</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Defect__c.object
<CustomObject>
    <description>This is a master object in Quality Central.</description>
    <fields>
        <fullName>Defect__c</fullName>
        <formula>Name + IF(ISBLANK(Defect_Code__c), &apos;&apos;, &apos;(&apos; + Defect_Code__c + &apos;)&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Defect</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NC_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Process</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Defect</label>
    <nameField>
        <label>Defect Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Defects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Document_Profile__c.object
<CustomObject>
    <fields>
        <fullName>ContentVersionId__c</fullName>
        <description>To Hold Primary Content Version Id</description>
        <inlineHelpText>To Hold Primary Content Version Id</inlineHelpText>
        <label>ContentVersionId</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Rev__c</fullName>
        <label>Current Rev</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type_Name__c</fullName>
        <formula>Document_Type__r.Title__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Document Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Followers__c</fullName>
        <label>Followers</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Initiating_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Initiating Site</label>
        <referenceTo>Manufacturing_Site__c</referenceTo>
        <relationshipLabel>Document Profiles</relationshipLabel>
        <relationshipName>Document_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owner_Name__c</fullName>
        <formula>Owner:User.FirstName + &apos; &apos; +Owner:User.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_File_Name__c</fullName>
        <label>Primary File Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process_Name__c</fullName>
        <formula>Process__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Process</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipName>Document_Types</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Document_Types</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SecondaryContentVersionId__c</fullName>
        <description>To Hold Secondary Content Version Id</description>
        <inlineHelpText>To Hold Secondary Content Version Id</inlineHelpText>
        <label>SecondaryContentVersionId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_File_Name__c</fullName>
        <label>Secondary File Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Inworks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prerelease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Preexpire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Void</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Document Profile</label>
    <nameField>
        <label>Document Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Non_Conformance__c.object
<CustomObject>
    <description>This is a Non Conformance object.</description>
    <fields>
        <fullName>BusinessUnit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Unit 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>unit2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>unit3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unit 4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Defect__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Defect</label>
        <referenceTo>Defect__c</referenceTo>
        <relationshipLabel>Non-Conformances</relationshipLabel>
        <relationshipName>Non_Conformances</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Followers__c</fullName>
        <label>Followers</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Initiating_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Initiating Site</label>
        <referenceTo>Manufacturing_Site__c</referenceTo>
        <relationshipLabel>Non-Conformances (Initiating Site)</relationshipLabel>
        <relationshipName>Non_Conformances1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NC_Source__c</fullName>
        <label>NC Source</label>
        <picklist>
            <picklistValues>
                <fullName>Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NC_Type__c</fullName>
        <inlineHelpText>Select either Product or Process to categorize the event. Based on this field, either &apos;Select Product&apos; or &apos;Select Process&apos; field is displayed.</inlineHelpText>
        <label>NC Type</label>
        <picklist>
            <picklistValues>
                <fullName>Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Owner_Name__c</fullName>
        <formula>Owner:User.FirstName + &apos; &apos; +Owner:User.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process_Name__c</fullName>
        <formula>Process__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Process</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Non-Conformances</relationshipLabel>
        <relationshipName>Non_Conformances</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Non-Conformances</relationshipLabel>
        <relationshipName>Non_Conformances</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Non-Conformance</label>
    <nameField>
        <displayFormat>NC-{00000}</displayFormat>
        <label>Non-Conformance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non-Conformances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process__c.object
<CustomObject>
    <description>This is a master object in Quality Central.</description>
    <fields>
        <fullName>Defect__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This needs to be deleted.</description>
        <label>Defect</label>
        <referenceTo>Defect__c</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Standard_Operational_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <description>This is a master object in Quality Central.</description>
    <fields>
        <fullName>Product__c</fullName>
        <formula>Name + IF(ISBLANK(Product_Number__c), &apos;&apos;, &apos;(&apos; + Product_Number__c + &apos;)&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Product Family</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Family</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/quickSearchController.cls
//**
//Quick Search controller
//Used to approve all tasks and changes
/*  
    v1.0        Qualityze Inc(MK)           9-SEPT-2016         
*/
public with sharing class quickSearchController {

transient public String docPrereleaseFilter{get;set;}
transient public String docCurrentFilter{get;set;}
transient public string sObjectName{get;set;}
transient public string docBookmarkFilter {get; Set;}
transient public String openNCFilter{get;set;}
transient public String workflowNCFilter{get;set;}
transient public String openCAPAFilter{get;set;}
    
 public quickSearchController(){
    }
    
public List<String> getSearchListValues(String ObjName, String FieldSetName,String returnType)
{
    List<String> returnList = new List<String> ();
    if(!string.isEmpty(ObjName) && !string.isEmpty(FieldSetName))
    {
        Schema.SObjectType SObjectTypeObj = Schema.getGlobalDescribe().get(ObjName);
        Schema.DescribeSObjectResult DescribeSObjectResultObj = SObjectTypeObj.getDescribe();
        Schema.FieldSet fieldSetObj = DescribeSObjectResultObj.FieldSets.getMap().get(FieldSetName);
        
        for(Schema.FieldSetMember m : fieldSetObj.getFields())
        {
            if(returnType == 'LABEL')
              returnList.add(m.getLabel());
            if(returnType == 'API')
              returnList.add(m.getFieldPath());
        }
    }
    return returnList;
}// end of function


public List<String> getHeaderLabels()
{
    List<String> tableHeaderLabelsList = new List<String>();
    if(sObjectName == 'Documents')
    {
        tableHeaderLabelsList= getSearchListValues('Document_Profile__c','Document_Search_List_Fields','LABEL');
    }
    if(sObjectName == 'NC')
    {
        tableHeaderLabelsList= getSearchListValues('Non_Conformance__c','NC_Search_List_Fields','LABEL');
    }

    return tableHeaderLabelsList;
}
public List<String> getTableFieldAPINames()
{
    List<String> tableFieldAPINameList = new List<String>();
    if(sObjectName == 'Documents')
    {
        tableFieldAPINameList= getSearchListValues('Document_Profile__c','Document_Search_List_Fields','API');
    }
    if(sObjectName == 'NC')
    {
        tableFieldAPINameList= getSearchListValues('Non_Conformance__c','NC_Search_List_Fields','API');
    }
    return tableFieldAPINameList;
}

 public List<Document_Profile__c> getDPList()
  {
    List<Document_Profile__c> dpList = new List<Document_Profile__c>();
    System.debug('-->sObjectName :'+sObjectName);
    System.debug('-->docPrereleaseFilter:'+docPrereleaseFilter);
    System.debug('-->docCurrentFilter:'+docCurrentFilter);
    System.debug('-->docBookmarkFilter:'+docBookmarkFilter);
    String loggedInUserId=UserInfo.getUserId();
    Set<String> StatusValues = new Set<String>();
    if(!string.isEmpty(docPrereleaseFilter))
        StatusValues.add(docPrereleaseFilter);
    if(!string.isEmpty(docCurrentFilter))
        StatusValues.add(docCurrentFilter);
    System.debug('-->StatusValues :'+StatusValues+'-->'+StatusValues.isEmpty());

    List<String> serachfieldList = getSearchListValues('Document_Profile__c','Document_Search_List_Fields','API');
    System.debug('-->serachfieldList :'+serachfieldList);

    String SearchString;
    if(serachfieldList.size() > 0)
    {
        SearchString = string.join(serachfieldList,',');
    //SearchString = SearchString + ',Id,Owner.Name,ContentVersionId__c,SecondaryContentVersionId__c,Secondary_File_Name__c,Primary_File_Name__c,Followers__c';
     SearchString = SearchString + ',Id,Owner.Name,ContentVersionId__c,SecondaryContentVersionId__c,Secondary_File_Name__c,Primary_File_Name__c,Followers__c,Name,Current_Rev__c,Title__c,Document_Type_Name__c,Owner_Name__c,Product_Name__c,Process_Name__c,Status__c,Effective_Date__c,Expiration_Date__c';
    }
    else
        SearchString = 'Id,Owner.Name,ContentVersionId__c,SecondaryContentVersionId__c,Secondary_File_Name__c,Primary_File_Name__c,Followers__c,Name,Current_Rev__c,Title__c,Document_Type_Name__c,Owner_Name__c,Product_Name__c,Process_Name__c,Status__c,Effective_Date__c,Expiration_Date__c';

    System.debug('-->SearchString :'+ SearchString);

    Set<String> SearchStringSet = new Set<String>(SearchString.split(','));
    List<String> FinalSearchStringList = new List<String>(SearchStringSet);
    String FinalSearchString = string.join(FinalSearchStringList,',');

    String queryFieldNames = QC_DynamicObjectHandler.getAccessibleFields('Document_Profile__c',FinalSearchString);

    if(sObjectName == 'Documents')
    {
        System.debug('-->Inside sObjectName:'+sObjectName);
        
        if(queryFieldNames != null && queryFieldNames != '')
        {
            if(!StatusValues.isEmpty() && string.isEmpty(docBookmarkFilter))
                dpList = database.query ('select ' + queryFieldNames + ' from Document_Profile__c where Status__c IN: StatusValues LIMIT 1000');
            else if(StatusValues.isEmpty() && !string.isEmpty(docBookmarkFilter))
                dpList = database.query ('select ' + queryFieldNames + ' from Document_Profile__c where Followers__c INCLUDES (\''+loggedInUserId+'\') LIMIT 1000');
            else if(!StatusValues.isEmpty() && !string.isEmpty(docBookmarkFilter))
                dpList = database.query ('select ' + queryFieldNames + ' from Document_Profile__c where (Status__c IN: StatusValues OR Followers__c INCLUDES (\''+loggedInUserId+'\'))  LIMIT 1000');
            else
              dpList = database.query ('select ' + queryFieldNames + ' from Document_Profile__c LIMIT 1000');
                
             System.debug('-->First dpList :'+dpList);
            return dpList;
         }
         else
         {
             return dpList;
          }
    }
    else
     {
        System.debug('-->Third dpList :'+dpList);
         return dpList;
      }
  }
  
  public Pagereference searchDPList()
  {
      return null;
  }

 public List<Non_Conformance__c> getNCList()
{
    System.debug('-->Inside sObjectName:'+sObjectName);
    List<String> searchfieldList = getSearchListValues('Non_Conformance__c','NC_Search_List_Fields','API');
    String SearchString;
    //serachfieldList.remove(null);
    SearchString = string.join(searchfieldList,',');
    SearchString = SearchString + ',Id,CreatedBy.Name,Owner.Name';

    System.debug('-->SearchString :'+ SearchString);

   // String queryFieldNames = QC_DynamicObjectHandler.getAccessibleFields('Non_Conformance__c', 'Name,OwnerId,Owner.Name,NC_Type__c,NC_Source__c,Product__r.Name,Process__r.Name,Defect__r.Name,BusinessUnit__c,Initiating_Site__r.Name,CreatedDate,CreatedBy.Name,NC_Status__c,Occurance_Date__c');
    String queryFieldNames = QC_DynamicObjectHandler.getAccessibleFields('Non_Conformance__c',SearchString);
    List<Non_Conformance__c> ncList = new List<Non_Conformance__c>();
     if(sObjectName == 'NC')
    {
        if(queryFieldNames != null && queryFieldNames != '')
        {
            if(string.isEmpty(openNCFilter) && string.isEmpty(workflowNCFilter))
                ncList = database.query ('select ' + queryFieldNames + ' from Non_Conformance__c ORDER BY createddate DESC LIMIT 9999');
            else if(!string.isEmpty(openNCFilter) && string.isEmpty(workflowNCFilter))
                ncList = database.query ('select ' + queryFieldNames + ' from Non_Conformance__c where NC_Status__c != \'Closed\' ORDER BY createddate DESC LIMIT 9999');
            else if(string.isEmpty(openNCFilter) && !string.isEmpty(workflowNCFilter))
                ncList = database.query ('select ' + queryFieldNames + ' from Non_Conformance__c where NC_Status__c =: workflowNCFilter  ORDER BY createddate DESC LIMIT 9999');
            else
                ncList = database.query ('select ' + queryFieldNames + ' from Non_Conformance__c ORDER BY createddate DESC LIMIT 9999');
            return ncList;
         }
         else
             return ncList;
    }
    else
    {
        return ncList;
    }
}



 public List<CAPA__c> getCAPAList()
{
    System.debug('-->Inside sObjectName:'+sObjectName);
    String queryFieldNames = QC_DynamicObjectHandler.getAccessibleFields('CAPA__c', 'Id,Name,OwnerId,Owner.Name,CAPA_Status__c,Reported_By__r.Name, CAPA_Source__c,Title__c,Problem_Statement__c,Criticality__c,Reported_Date__c,Department__c,Sites_Impacted__c,CreatedDate,CreatedBy.Name,Reported_By__c,Occurance_Date__c,Department__r.Name');
    List<CAPA__c> capaList = new List<CAPA__c>();
     if(sObjectName == 'CAPA')
    {
        if(queryFieldNames != null && queryFieldNames != '')
        {
            if(!string.isEmpty(openCAPAFilter))
                capaList = database.query ('select ' + queryFieldNames + ' from CAPA__c where CAPA_Status__c != \'Closed\' ORDER BY createddate DESC LIMIT 9999');
            else
                capaList = database.query ('select ' + queryFieldNames + ' from CAPA__c ORDER BY createddate DESC LIMIT 9999');
            return capaList;
         }
         else
             return capaList;
    }
    else
    {
        return capaList;
    }
}


@RemoteAction
public static pagereference bookMarkdocremotefunc(String docprofileId, String bookmarkValue)
{
    String queryFieldNames = QC_DynamicObjectHandler.getAccessibleFields('Document_Profile__c', 'Id,Followers__c');
    System.debug('-->Inside bookMarkDoc:'+docprofileId);
    String loggedInUserId=UserInfo.getUserId();
    List<Document_Profile__c> dpList = new List<Document_Profile__c>();
    if(!String.isBlank(docprofileId) && !String.isEmpty(docprofileId))
    {
         if(queryFieldNames != null && queryFieldNames != '')
        {
                dpList = database.query ('select ' + queryFieldNames + ' from Document_Profile__c where Id=:docprofileId limit 9999');
                System.debug('-->Inside bookMarkDoc dpList:'+dpList);
                System.debug('-->Oustide IF :'+ dpList[0].Followers__c);
                if(bookmarkValue == 'bookmark')
                 {
                    if(dpList != null && dpList.size() > 0 &&  dpList[0].Followers__c != null && !dpList[0].Followers__c.contains(loggedInUserId) )
                    {
                            System.debug('-->Inside IF :'+ dpList[0].Followers__c);
                            dpList[0].Followers__c = dpList[0].Followers__c+';'+loggedInUserId;
                            
                    }
                    else
                        dpList[0].Followers__c = loggedInUserId;
                }// End of if
                if(bookmarkValue == 'remove')
                {
                    if(dpList != null && dpList.size() > 0 &&  dpList[0].Followers__c != null && dpList[0].Followers__c.contains(loggedInUserId) )
                    {
                            List<String> follwersStr = dpList[0].Followers__c.split(',');
                            Set<String> follwersSet = new Set<String>(follwersStr);
                            follwersSet.remove(loggedInUserId);
                            List<String> follwersStrList = new List<String>(follwersSet);
                            String followerString = string.join(follwersStrList,',');
                            dpList[0].Followers__c = followerString;
                            
                    }
                }

                System.debug('-->Followers__c :'+ dpList[0].Followers__c);
                update dpList;
        }// End of If condition
    }
    
    return null;
}

}