src/objects/Custom_Fields__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Custom Fields</label>
</CustomObject>

src/objects/Custom_Labels__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>This is to provide custom names for field labels and section labels</description>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <label>Custom Labels</label>
</CustomObject>

src/objects/Dev_Only__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Settings for developers only</description>
    <fields>
        <fullName>API_Version__c</fullName>
        <defaultValue>&apos;33.0&apos;</defaultValue>
        <description>e.g. 33.0</description>
        <label>API_Version</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Namespace_Prefix__c</fullName>
        <defaultValue>&apos;QPMS&apos;</defaultValue>
        <label>Namespace Prefix</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Dev Only</label>
</CustomObject>

src/objects/Error_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings that control your error management configuration.</description>
    <fields>
        <fullName>Disable_Error_Handling__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, QPMS&apos;s error handling framework is disabled.</description>
        <inlineHelpText>If checked, QPMS&apos;s error handling framework is disabled.</inlineHelpText>
        <label>Disable Error Handling</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Debug__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Turn this on to enable debug statements in managed package code.</description>
        <inlineHelpText>Turn this on to enable debug statements in managed package code.</inlineHelpText>
        <label>Enable Debug</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Error_Notifications_On__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag that determines whether to send error notifications.</description>
        <inlineHelpText>Check this if you&apos;d like the system to post notifications for certain type of errors.</inlineHelpText>
        <label>Error Notifications</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Error_Notifications_To__c</fullName>
        <description>Who should receive error notifications.</description>
        <inlineHelpText>Select the type of user to send notifications to.</inlineHelpText>
        <label>Error Notification Recipients</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Store_Errors_On__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag that indicates whether errors are going to be stored in the database.</description>
        <inlineHelpText>Check this if you&apos;d like errors to be stored in the database.</inlineHelpText>
        <label>Store Errors</label>
        <type>Checkbox</type>
    </fields>
    <label>Error Settings</label>
</CustomObject>

src/objects/Lookup_Filter__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>This is to provide custom filetrs for lookup field</description>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>120</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>Object Api Name</description>
        <label>Object Name</label>
        <length>120</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Lookup Filter</label>
</CustomObject>

src/objects/QC_settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Org specific settings</description>
    <fields>
        <fullName>Action_Plan_RecordTypeId__c</fullName>
        <label>Action Plan RecordTypeId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AdhocTask_Actions_RecordTypeId__c</fullName>
        <label>AdhocTask Actions RecordTypeId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Connected_App_consumer_key__c</fullName>
        <label>Connected App consumer key</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Connected_App_consumer_secret__c</fullName>
        <label>Connected App consumer secret</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enable_CAPA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable CAPA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_DOC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable DOC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_NC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable NC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Instance_Name__c</fullName>
        <inlineHelpText>Salesforce instance name (e.g. na41, ap2, eu5, etc.)</inlineHelpText>
        <label>Instance Name</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Digital_Signature_Needed__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag To show or hide digital signature</description>
        <label>Is Digital Signature Needed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_External_System_Capa_Reference_Needed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is External System Capa Reference Needed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Approvers__c</fullName>
        <defaultValue>10</defaultValue>
        <label>Max Approvers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Need_Additional_Resolution_Codes__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Need Additional Resolution Codes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_Of_Days_For_Alerts__c</fullName>
        <label>Number Of Days For Alerts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Root_Cause_RecordTypeId__c</fullName>
        <label>Root Cause RecordTypeId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Verification_Plan_RecordTypeId__c</fullName>
        <label>Verification Plan RecordTypeId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>QC_settings</label>
</CustomObject>

src/classes/QC_custom_settings.cls
// @description Helper class that retrieves custom settings and sets defaults.
public with sharing class QC_custom_settings {
    
    public static String customLabelKeys{get;set;}
    public static Map<String,Custom_Labels__c> customLabels{get;set;}
    //To get all custom field details of custom setting Custom_Fields__c
    static{
    	customLabelKeys='';
    	customLabels=Custom_Labels__c.getAll();
    	for(String key : customLabels.keySet()){
    		customLabelKeys+=key;
    	}
    }
    public static String FilterKeys{get;set;}
    public static Map<String,Lookup_Filter__c> LookupFilter{get;set;}
    public static Map<String,String> Subkey{get;set;}
    //To get all custom field details of custom setting Custom_Fields__c
    static{
        FilterKeys='';
        LookupFilter=new Map<String,Lookup_Filter__c>();
        Subkey=new Map<String,String>();
        for(Lookup_Filter__c LF : Lookup_Filter__c.getAll().values()){
            FilterKeys+=LF.Object_Name__c;
            LookupFilter.put(LF.Field_Name__c, LF);
            if(!Subkey.containsKey(string.valueof(LF.Object_Name__c))){	
                
                Subkey.put(string.valueof(LF.Object_Name__c),(string.valueof(LF.Field_Name__c)));
            }else{
                
                Subkey.put(string.valueof(LF.Object_Name__c), Subkey.get(string.valueof(LF.Object_Name__c))+string.valueof(LF.Field_Name__c));
            }
        }
        
        system.debug('FilterKeys=='+FilterKeys);
        system.debug('Subkey=='+Subkey);
    }
    
    public QC_custom_settings(NonConformance controller){}
    
    //Usage in VisualForce Page --> {! $Setup.Dev_Only__c.Namespace_Prefix__c }
    public static string getPrefix(){
       return Dev_Only__c.getOrgDefaults().Namespace_Prefix__c;
    }
    
    public static string getAPI_Version(){
        return Dev_Only__c.getOrgDefaults().API_Version__c;
    }
    
    public static string getServer(){
       return QC_settings__c.getOrgDefaults().Instance_Name__c;
    }
    
    public static String getConsumerKey(){
        return QC_settings__c.getOrgDefaults().Connected_App_consumer_key__c;
    }
    
    public static String getConsumerSecret(){
       return QC_settings__c.getOrgDefaults().Connected_App_consumer_secret__c; 
    }
    
    public static Integer getMaxApprovers(){
      return Integer.valueOf(QC_settings__c.getOrgDefaults().Max_Approvers__c);
    }
    
    public static Boolean getDigitalSignatureNeeded(){
        return Boolean.valueOf(QC_settings__c.getOrgDefaults().Is_Digital_Signature_Needed__c);
    }
    
    public static Boolean getNeedAdditionalResolutionCodes(){
        return Boolean.valueOf(QC_settings__c.getOrgDefaults().Need_Additional_Resolution_Codes__c);
    }
    
    public static Boolean getExternalSystemCapaReferenceNeeded(){
    	return Boolean.valueOf(QC_settings__c.getOrgDefaults().Is_External_System_Capa_Reference_Needed__c);
    }
    
    
    public static Integer getNumberOfDaysForAlerts(){
        system.debug('Integer.valueOf(QC_settings__c.getOrgDefaults().Number_Of_Days_For_Alerts__c)   '+Integer.valueOf(QC_settings__c.getOrgDefaults().Number_Of_Days_For_Alerts__c));
        return Integer.valueOf(QC_settings__c.getOrgDefaults().Number_Of_Days_For_Alerts__c);
    }
    
    public static String getRootCauseId(){
       return QC_settings__c.getOrgDefaults().Root_Cause_RecordTypeId__c; 
    }
    
    public static String getActionPlanId(){
       return QC_settings__c.getOrgDefaults().Action_Plan_RecordTypeId__c; 
    }
    
    public static String getVerificationPlanId(){
       return QC_settings__c.getOrgDefaults().Verification_Plan_RecordTypeId__c; 
    }
    
    public static String getAdhocId(){
       return QC_settings__c.getOrgDefaults().AdhocTask_Actions_RecordTypeId__c; 
    }
    
    public static Boolean getEnableNC(){
    	return Boolean.valueOf(QC_settings__c.getOrgDefaults().Enable_NC__c);
    }
    
    public static Boolean getEnableCAPA(){
        return Boolean.valueOf(QC_settings__c.getOrgDefaults().Enable_CAPA__c);
    }
    
    public static Boolean getEnableDOC(){
        return Boolean.valueOf(QC_settings__c.getOrgDefaults().Enable_DOC__c);
    }
    
    public QC_custom_settings() {
        
    }
    
    public QC_custom_settings(ApexPages.StandardController controller) {
        
    }
    
    public QC_custom_settings(Component_Handler controller) {
        
    }
    
    public QC_custom_settings(FileAttachmentController controller){
        
    }
    
    public QC_custom_settings(CAPA controller){
        
    }
    
     public QC_custom_settings(DocumentProfileControllerExt controller){
        
    }
    
    //storing user-level custom settings in-memory to avoid trying to insert/update them 
    //twice and thus trigger the "duplicate OwnerId" error
    static Error_Settings__c errorSettings;
    
    //storing org-level custom settings in-memory to avoid slowing down the settings page
    static Error_Settings__c orgErrorSettings;    
    
    /*******************************************************************************************************
    * @description Returns the default Error Handling settings. 
    * @return Error_Settings__c Custom settings record for Error Handling configuration. At the org level, if no user 
    * level settings are defined. The ID field should be checked to determine if the returned record already
    * exists or doesn't exist in the database.
    */
    public static Error_Settings__c getErrorSettings() {
        if(Test.isRunningTest() && errorSettings == null) {
            errorSettings = new Error_Settings__c();
            configErrorSettings(errorSettings, null);
        } else if(errorSettings == null) {
            errorSettings = Error_Settings__c.getInstance();
            if(errorSettings.Id == null)
                errorSettings = getOrgErrorSettings();
        }    
        return errorSettings;
    }
    
    /*******************************************************************************************************
    * @description Returns the org-level Error settings. Default org-level settings will be created 
    * if none exist. Meant to be called only from settings page and install script.
    * @return Error_Settings__c Org-level settings for Errors.
    */
    public static Error_Settings__c getOrgErrorSettings() {
        if(orgErrorSettings == null) {
            orgErrorSettings = Error_Settings__c.getOrgDefaults();
            if(orgErrorSettings.Id == null) {
                configErrorSettings(orgErrorSettings, null);
                if(!Test.isRunningTest())
                    upsert orgErrorSettings;
            }
        }
        return orgErrorSettings;
    }
    
    private static void configErrorSettings(Error_Settings__c es, String notificationsTo) {   
        es.Store_Errors_On__c = true;
        es.Error_Notifications_On__c = true;
        es.Error_Notifications_To__c = ERR_Notifier.NotificationOptions.sysAdmins;
        es.Disable_Error_Handling__c = false;
        es.Enable_Debug__c = false;
    }
    
    /*******************************************************************************************************
    * @description Creates instance of settings to use in tests. It does not insert it, 
    * but all other methods will see these settings as the configured settings.
    * @parameter mySettings Settings instance with the values to set.
    * @return Error_Settings__c The configured settings.
    **/
    public static Error_Settings__c getErrorSettingsForTests(Error_Settings__c mySettings) {
        if(errorSettings == null)
           errorSettings = new Error_Settings__c();
           
        errorSettings.Error_Notifications_On__c = mySettings.Error_Notifications_On__c;   
        errorSettings.Error_Notifications_To__c = mySettings.Error_Notifications_To__c;
        errorSettings.Store_Errors_On__c = mySettings.Store_Errors_On__c;
        orgErrorSettings = errorSettings;
        return errorSettings;  
    }   
    
    public static string removeNamespaceFromFieldName(string fieldNameThatMightHaveANamespace) {
        string stringToReturn = '';
        string namespacePrefix = getPrefix();
        if (string.isBlank(namespacePrefix)) {
            // No namespace detected in the environment so won't even try to remove the namespace
            return fieldNameThatMightHaveANamespace;
        }
        string namespacePrefixWithUnderscores = namespacePrefix + '__';
        // need to ask mahesh
        if(fieldNameThatMightHaveANamespace.startsWithIgnoreCase(namespacePrefixWithUnderscores)){
            stringToReturn = fieldNameThatMightHaveANamespace.removeStart(namespacePrefixWithUnderscores);
        }else{
        	stringToReturn = fieldNameThatMightHaveANamespace;    
        }
        
        return stringToReturn;
    }
}