src/objects/Document_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Auto_Expire__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Expire</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_of_Purge__c</fullName>
        <description>Date of Purge:</description>
        <label>Date of Purge</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pre_Release_Duration_Date__c</fullName>
        <description>PreRelease Duration Date (document is released)</description>
        <label>Pre Release Duration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Inworks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prerelease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Preexpire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Void</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Document Profile</label>
    <nameField>
        <label>Document Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BatchHandler.cls
global class BatchHandler implements Database.Batchable<sObject>{
        
        global BatchHandler(){
            // Batch Constructor
        }
        
        // Start Method
        global Database.QueryLocator start(Database.BatchableContext BC){
            Date mydate=system.today();
            //below line updated by balu by adding another filter for effective auto expire
            string Obsolete='Obsolete';
            string Current='Current';
            string Prerelease='Prerelease';
            boolean truevar=true;
            //String query ='select id,status__c from Document_Profile__c where (status__c!= \'Obsolete\' AND  Date_of_Purge__c=: mydate)OR(status__c!= \'Current\' AND  Effective_Date__c=: mydate)OR(Auto_expire=:true and Expiration_Date__c =:mydate )OR(status__c!= \'Prerelease\' AND  Pre_Release_Duration_Date__c=: mydate) ';
            String query ='select id,status__c,Auto_Expire__c,Effective_Date__c,Expiration_Date__c,Pre_Release_Duration_Date__c,Date_of_Purge__c from Document_Profile__c where (status__c!=: Obsolete AND  Date_of_Purge__c=: mydate)OR(status__c!=:Current AND  Effective_Date__c=: mydate) OR(Auto_expire__c=:truevar and Expiration_Date__c =:mydate )OR(status__c!=: Prerelease AND  Pre_Release_Duration_Date__c=: mydate) ';
            system.debug('inside Qc_Batch class '+query);
            return Database.getQueryLocator(query);
        }
        
        // Execute Logic
        global void execute(Database.BatchableContext BC, List<sObject> objs){
            Schema.SObjectType token;
            string namespace=qc_custom_settings.getPrefix();
            if(namespace!=null){
            namespace+='__';
            }else{
            namespace='';
            }
            if(objs!=null&&!objs.isEmpty()){           
                token = objs[0].Id.getSObjectType();    
            }
            Document_profile__C  d;
            Date mydate=system.today();
            if(string.valueOf(token).containsIgnoreCase(namespace+'Document_profile__C')){
                for(sObject obj :objs){
                		if(obj.get(namespace+'Effective_Date__c')==mydate){
                        obj.put(namespace+'Status__c','Current');
                		}
                		if(obj.get(namespace+'Pre_Release_Duration_Date__c')==mydate){
                        obj.put(namespace+'Status__c','Prerelease');
                		}
                		if(obj.get(namespace+'Date_of_Purge__c')==mydate){
                        obj.put(namespace+'Status__c','Obsolete');
                		}
                		if(obj.get(namespace+'Expiration_Date__c')==mydate&&obj.get(namespace+'Auto_expire__c')==true){
                		obj.put(namespace+'Status__c','Expired');
                		}		
                }
            }
            update objs;
        }
        
        global void finish(Database.BatchableContext BC){
            // Logic to be Executed at finish,if you want to send email to you then write code here 
            //This code will execute in last when all record are updated
        }
}