src/objects/Error__c.object
<CustomObject>
    <description>Contains errors generated from the QPMS package during normal operations.</description>
    <fields>
        <fullName>Context_Type__c</fullName>
        <description>Context that generated the error, if known.</description>
        <inlineHelpText>Context that generated the error, if known.</inlineHelpText>
        <label>Context Type</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Datetime__c</fullName>
        <defaultValue>now()</defaultValue>
        <description>Date &amp; time the error occurred</description>
        <inlineHelpText>Date &amp; time the error occurred</inlineHelpText>
        <label>Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Email_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether an email notification has been sent regarding this error.</description>
        <inlineHelpText>Indicates whether an email notification has been sent regarding this error.</inlineHelpText>
        <label>Email Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Error_Type__c</fullName>
        <description>Type of error that occurred</description>
        <inlineHelpText>Type of error that occurred</inlineHelpText>
        <label>Error Type</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Full_Message__c</fullName>
        <description>Full text of the error message</description>
        <inlineHelpText>Full text of the error message</inlineHelpText>
        <label>Full Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Object_Type__c</fullName>
        <description>Type of object on which the error occurred, if known.</description>
        <inlineHelpText>Type of object on which the error occurred, if known.</inlineHelpText>
        <label>Object Type</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Posted_in_Chatter__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the error has been posted in Chatter.</description>
        <inlineHelpText>Indicates whether the error has been posted in Chatter.</inlineHelpText>
        <label>Posted in Chatter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_URL__c</fullName>
        <description>A link to the record which caused the error, if available.</description>
        <inlineHelpText>A link to the record which caused the error, if available.</inlineHelpText>
        <label>Record URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <description>Stack trace for the thrown error, if available at runtime.</description>
        <inlineHelpText>Stack trace for the thrown error, if available at runtime.</inlineHelpText>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Error</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Error Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ERR_Handler.cls
/* @description Helps determine if errors occurred during the DML operations performed during the transaction, and with 
 * the necessary storing and notification of these errors.
 */ 
public with sharing class ERR_Handler {
    
    /*******************************************************************************************************
    * @description Creates an error record from an exception, stores it in the database (if enabled), and sends error
    *              notifications (if enabled).
                   This method should be used from inside the NPSP package, instead of the same one with that same name
                   that takes a String instead of an Enum as the second parameter.
    * @param e Exception to create error record from.
    * @return context The context the exception was raised on.
    */
    public static void processError(Exception e, ERR_Handler_API.Context context) {     
        processError(e, context.name());   
    }
    
    /*******************************************************************************************************
    * @description Creates an error record from an exception, stores it in the database (if enabled), and sends error
    *              notifications (if enabled).
    * @param e Exception to create error record from.
    * @return context The context the exception was raised on.
    */
    public static void processError(Exception e, String context) {     
        if(e != null) {         
            Error__c error = createError(e);
            processErrors(new Error__c[]{error}, context);
        }   
    }
    
    /*******************************************************************************************************
    * @description Stores errors in the database (if enabled), and sends error notifications (if enabled).
    * @param errorRecords The errors to store.
    * @param context The context the errors were raised on.
    * @return void
    */
    public static void processErrors(List<Error__c> errorRecords, String context) {
        
        if(errorRecords != null && errorRecords.size() > 0) {
            if(ApexPages.currentPage() != null) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, errorRecords[0].Full_Message__c));
            }
                    
            if(QC_custom_settings.getErrorSettings().Store_Errors_On__c) {
                if(QC_DynamicObjectHandler.checkCreateUpdateAccess('Error__c','Context_Type__c,Error_Type__c,Full_Message__c,Object_Type__c,Stack_Trace__c,Record_URL__c,Posted_in_Chatter__c,Email_Sent__c,Datetime__c','create'))
                {
                   Database.insert(errorRecords, false);
                }
            }
            //ERR_Notifier takes care of checking the settings itself.
            ERR_Notifier.sendErrorNotifications(context);
        }
    }
    
    /*******************************************************************************************************
    * @description Creates an error record from an exception.
    * @param e Exception to create error record from.
    * @return Error__c Error record.
    */
    private static Error__c createError(Exception e) {
        Error__c error = new Error__c();
        error.Datetime__c = System.now();        
        error.Error_Type__c = e.getTypeName();
        error.Full_Message__c = e.getMessage();
        //Putting it into a local string to see if that helps storing the stack trace when we
        //are in a managed package.
        String stackTrace = e.getStackTraceString();
        String message = 'No stacktrace available at the time of saving the record. ';
        
        error.Stack_Trace__c = message + stackTrace;
        return error;
    }
}